# Generated by Django 3.1.3 on 2020-11-28 10:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otpcode', models.IntegerField()),
                ('date_time', models.DateTimeField(default=datetime.datetime(2020, 11, 28, 16, 9, 17, 942518))),
                ('response', models.IntegerField(default=-1)),
                ('parentref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.parent')),
            ],
        ),
    ]
