# Generated by Django 3.1.3 on 2020-11-28 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_otpverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='parentref',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='parentemail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 16, 33, 54, 466750)),
        ),
    ]
