# Generated by Django 3.1.3 on 2020-12-01 15:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0021_auto_20201201_2113'),
        ('account', '0003_auto_20201127_2049'),
        ('login', '0003_auto_20201128_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 21, 13, 35, 373548)),
        ),
        migrations.CreateModel(
            name='ParentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_email', models.EmailField(max_length=254)),
                ('request_type', models.CharField(max_length=20)),
                ('approved_by_coordinator', models.BooleanField(default=False)),
                ('viewed_by_coordinator', models.BooleanField(default=False)),
                ('approved_by_staff', models.BooleanField(default=False)),
                ('viewed_by_staff', models.BooleanField(default=False)),
                ('coordinatorref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.teacher')),
                ('studentref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.student')),
            ],
        ),
    ]
