# Generated by Django 3.1.3 on 2020-12-03 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20201203_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 21, 30, 59, 169629)),
        ),
        migrations.AlterField(
            model_name='parentrequest',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 3, 21, 30, 59, 170628), null=True),
        ),
    ]
