# Generated by Django 3.1.3 on 2020-12-05 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20201204_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 20, 45, 14, 555508)),
        ),
        migrations.AlterField(
            model_name='parentrequest',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 5, 20, 45, 14, 556669), null=True),
        ),
    ]
