# Generated by Django 3.1.3 on 2020-12-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDataFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='StudentData', max_length=30)),
                ('file', models.FileField(upload_to='')),
                ('upload_date_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
