# Generated by Django 3.1.3 on 2020-12-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdatafileupload',
            name='file',
            field=models.FileField(upload_to='static/schooldata'),
        ),
    ]
