# Generated by Django 3.1.3 on 2020-11-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='classstudent',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
    ]
