# Generated by Django 3.1.3 on 2020-11-15 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_classstudent_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.BooleanField()),
                ('studentref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.student')),
            ],
        ),
    ]
