# Generated by Django 3.1.3 on 2020-11-15 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_attendancestudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancestudent',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
