# Generated by Django 3.1.3 on 2020-11-15 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_attendancestudent_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancestudent',
            name='date',
        ),
    ]
