# Generated by Django 3.1.3 on 2020-11-21 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_attendancestudent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancestudent',
            name='studentref_name',
            field=models.CharField(default='name', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancestudent',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 21, 17, 27, 25, 108383)),
        ),
    ]
