# Generated by Django 3.1.3 on 2020-11-21 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_auto_20201121_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancestudent',
            name='studentref_grade',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='attendancestudent',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 21, 20, 49, 41, 894122)),
        ),
    ]
