# Generated by Django 3.1.3 on 2020-11-28 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0018_auto_20201128_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancestudent',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 28, 16, 9, 17, 939527)),
        ),
    ]
