# Generated by Django 3.1.3 on 2020-12-01 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0020_auto_20201128_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancestudent',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 1, 21, 13, 35, 365569)),
        ),
    ]
