# Generated by Django 3.1.3 on 2020-12-01 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0021_auto_20201201_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancestudent',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 1, 21, 49, 6, 729651)),
        ),
    ]
