# Generated by Django 3.1.3 on 2020-12-02 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0023_auto_20201202_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancestudent',
            name='on_leave',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='classstudent',
            name='on_leave',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='attendancestudent',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 2, 21, 2, 27, 582486)),
        ),
        migrations.AlterField(
            model_name='classstudent',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 2, 21, 2, 27, 578499), null=True),
        ),
    ]
