# Generated by Django 3.1.3 on 2020-12-03 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0027_auto_20201203_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fathers_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mothers_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='attendancestudent',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 3, 21, 30, 59, 165615)),
        ),
        migrations.AlterField(
            model_name='classstudent',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 3, 21, 30, 59, 164644), null=True),
        ),
    ]
