# Generated by Django 3.1.3 on 2020-12-04 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0028_auto_20201203_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='block',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='attendancestudent',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 4, 21, 22, 59, 572390)),
        ),
        migrations.AlterField(
            model_name='classstudent',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 4, 21, 22, 59, 572390), null=True),
        ),
    ]
