# Generated by Django 3.1.3 on 2020-12-16 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0037_auto_20201216_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeroomClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('section', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='classstudent',
            name='is_homeroomclassstudent',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='attendancestudent',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 12, 18, 16, 135901)),
        ),
        migrations.AlterField(
            model_name='classstudent',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 12, 18, 16, 133905), null=True),
        ),
    ]
