# Generated by Django 3.1.3 on 2020-12-16 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0039_auto_20201216_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='is_homeroom',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='classmodel',
            name='section',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='attendancestudent',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 12, 22, 26, 22198)),
        ),
        migrations.AlterField(
            model_name='classstudent',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 12, 22, 26, 22198), null=True),
        ),
    ]
