# Generated by Django 3.1.3 on 2020-12-16 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0043_auto_20201216_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancestudent',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 12, 28, 0, 918939)),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='section',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='classstudent',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 12, 28, 0, 915947), null=True),
        ),
    ]
