# Generated by Django 3.1.3 on 2020-12-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201127_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='verify_permissions',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
