# Generated by Django 3.1.3 on 2020-12-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classteachergrades',
            field=models.CharField(help_text='Separate sections by commas', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_classteacher',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
